INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMINISTRADOR');
INSERT INTO roles(name) VALUES('ROLE_VISUALIZADOR');
INSERT INTO roles(name) VALUES('ROLE_LIDER_PROYECTO');